### ISSUE TITLE
add repo names to README

### ISSUE THREAD

**Issue by aaronlippold** [CMSgov/cms-ars-3.1-moderate-aws-foundations-cis-overlay#1]
"For every successive run, follow these steps to always have the latest version of this overlay and dependent profiles:

cd profiles/\<baseline-repo\>
git pull
cd ../\<overlay-repo\>
git pull
bundle install"

**Comment by karikarshivani** [comment]
Now that we're not cloning the baseline repo, I believe that the instructions will change.
To prevent potential caching issues, should we ask users to clone the overlay repo for every successive run?
Thoughts? @rx294 @ejaronne

**Comment by ejaronne** [comment]
Yes, ask them to pull the overlay like the current readmes do

**Comment by karikarshivani** [comment]
All the READMEs have been updated ([commit link](https://github.com/CMSgov/cms-ars-3.1-moderate-aws-foundations-cis-overlay/commit/53a6572f18f554bd6ee1ba534e907ac927e106f4))
The version number in inspec.yml was updated to prevent potential caching issues.
Thanks @aaronlippold @ejaronne
