### ISSUE TITLE
Remove password age and length from user inputs

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/cms-ars-3.1-moderate-aws-foundations-cis-overlay#6]
On the README, these are already set in the inspec.yml and shouldn't be suggested to be edited in an inputs file via the README, nor in the template.yml. (Do we even need the template.yml?)

**Comment by karikarshivani** [comment]
@ejaronne I would think that it's good to have the template file so that they don't have to write up their own inputs file from scratch.
@rx294 thoughts?
