### ISSUE TITLE
update README archive run steps

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/cms-ars-3.1-moderate-aws-foundations-cis-overlay#7]
https://github.com/CMSgov/cms-ars-3.1-moderate-aws-foundations-cis-overlay#running-this-overlay-from-a-local-archive-copy

isn't really doing an "inspec archive" bundle to really be portable.  See the CMS redhat7 version for example.

**Comment by karikarshivani** [comment]
Fix in PR #8 @ejaronne
