### ISSUE TITLE
remove the key age, password length, and cred age from README tailoring

### ISSUE THREAD

**Issue by ejaronne** [CMSgov/cms-ars-3.1-moderate-aws-foundations-cis-overlay#9]
Since these are now declared/set in the inspec.yml, and should not be set by the user, please remove mention of these from the README:

# Used by InSpec check 1.4
# Description: Maximum aws key age
aws_key_age: 60

# Used by InSpec check 1.9
# Description: Password length
pwd_length: 12

# Used by InSpec check 1.11
# Description: Maximum IAM account age
aws_cred_age: 60

**Comment by karikarshivani** [comment]
@ejaronne PR #8 includes this fix. Thank you!
